name: 'Livin Strength & Conditioning'
favicon: null
layout_spectrum: 0.30658796010538936
typography_spectrum: 0.8793340581469238
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.28117068600840867
  lightness: 0.3943592004943639
  saturation: 0.7520461140666157
  rhythmicContrast: 0.2632440796587616
purpose: []
