name: 'Livin Strength & Conditioning'
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0
title: 'Livin Strength & Conditioning'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#029cdc'
    - '#f1f1f1'
    - '#a6d6ea'
    - '#40add5'
    - '#68c1dd'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
